### ISSUE TITLE
Functionality for submitting and scanning license requests in blockchain

### ISSUE THREAD

**Issue by miloszm** [dusk-network/citadel#51]
#### Summary
For realization of the Citadel protocol, we need a functionality for submitting license requests into blockchain in a form of recipient-less transactions, and also for scanning the relevant requests from blockchain.

#### Possible solution design or implementation
Solution should be based on the approach similar to the one used in wallet-cli and wallet-core.

#### Additional context
We need to make sure that recipent-less transactions will be accepted by the blockchain.

**Comment by xevisalle** [comment]
Done in moat.
