### ISSUE TITLE
Specify and implement lifecycle mechanisms for License data

### ISSUE THREAD

**Issue by miloszm** [dusk-network/citadel#53]
#### Summary
License data needs mechanism to enforce its lifecycle, some elements need to expire, or compensation is needed should license not be issued. Such mechanisms need to be specified and implemented.

#### Possible solution design or implementation
Some data needs to expire based on the number of Dusk blocks elapsed since their inception. Delay in receiving a license exceeding certain limit needs to cause a submission of a compensating/penalizing transaction. Details and implementation should be provided by this issue.

**Comment by xevisalle** [comment]
Closing because this should be addressed in Rusk / Moat (Application Layer).
