### ISSUE TITLE
Design, implement and document Citadel request authoring process

### ISSUE THREAD

**Issue by miloszm** [dusk-network/citadel#60]
#### Summary
Program moat allows submitting requests to the Dusk blockchain, the requests can then be scanned and processed by relevant license providers. A request to be submitted needs first to be created, in some physical form, for example as json file. We need to describe the format of such file and the process for gathering all the required data for it.

#### Possible solution design or implementation
Solution involves definition of an exact json (or other type) object and explanation of the origin, meaning and format of all data items which need to be entered into the fields of such json object.

#### Additional context
Documentation and tests for the above should be a part of the moat project.

**Comment by miloszm** [comment]
After discussion with Xavi, Request will be created in the following way:

User enters two values:
ssk_user: secret spend key of one of the user's wallet addresses
psk_lp: license provider's public key

both values are entered as hexadecimally encoded string of bytes

they can be entered as command line parameters or via a json configuration file

then the following transformations will lead to request creation:
```
psk = ssk.public_spend_key();
lsa = psk.gen_stealth_address(&JubJubScalar::random(rng));
lsk = ssk.sk_r(&lsa);
k_lic = JubJubAffine::from(GENERATOR_EXTENDED * sponge::truncated::hash(&[(*lsk.as_ref()).into()]));
request = Request::new(&psk_lp, &lsa, &k_lic, rng);

```
The request can then be serialized (using rkyv) and submitted into the blockchain.

**Comment by xevisalle** [comment]
Done in moat repo.
