### ISSUE TITLE
Add a non-panicking method for verifying session

### ISSUE THREAD

**Issue by miloszm** [dusk-network/citadel#87]
#### Summary
Current implementation of session verify panics if session fails the verification. For usage in CLI we need a non-panicking version so that we can continue operation after verification fails.

#### Possible solution design or implementation
Move the current implementation to a new function, but returning boolean instead of panicking. Then, convert the current function to use the new one but asserting on the returned boolean.

#### Additional context
Needed for the Citadel/Moat CLI

**Comment by xevisalle** [comment]
Done.
